# These are supported funding model platforms

github: []
patreon: PegasusHeavyIndustries
open_collective: []
ko_fi: []
tidelift: []
community_bridge: []
liberapay: []
issuehunt: []
lfx_crowdfunding: []
polar: []
buy_me_a_coffee: []
custom: []

